// build-registry-trust.test.mjs — D-06 v0.2 build-side extraction tests
// (Phase 10, Plan 10-02). node:test + node:assert/strict + .mjs — MATCHES the
// existing registry .test.mjs files (NOT vitest).
//
// The build reads OKF v0.2 concept frontmatter (generated/verified/stale_after/
// status/sources) WHEN PRESENT via the existing parseBundle .passthrough()
// frontmatter (structure.mjs:35-37 — this task only READS, never extends the
// ConceptFrontmatter zod schema, never touches the CLI ManifestSchema — D-06
// guardrail). summarizeTrustBundle rolls the per-concept tiers up into the
// bundle-level trust_summary shape (a mirror of the website's lib/trust.ts
// summarizeTrust — the canonical consumer-side contract): flat tier counts +
// tier_counts + dated-evidence rows with neutral glyphs only (D-09: NEVER a
// 🟢/🔵/🟡 badge). Absent v0.2 frontmatter → the honest all-unverified
// summary, never undefined, never an error.
//
// FIXTURE DISCIPLINE: hermetic in-test tmp bundle dirs, same as
// build-registry-materialize.test.mjs.
import { test } from "node:test";
import assert from "node:assert/strict";
import { mkdtemp, mkdir, writeFile, rm } from "node:fs/promises";
import { join, dirname } from "node:path";
import { tmpdir } from "node:os";
import { materializeConcepts, summarizeTrustBundle } from "../scripts/build-registry.mjs";

/** Build a tmp bundle dir with the given {relPath: content} files. Returns dir. */
async function makeBundle(files) {
  const dir = await mkdtemp(join(tmpdir(), "okfhub-trust-"));
  for (const [relPath, content] of Object.entries(files)) {
    const full = join(dir, relPath);
    await mkdir(dirname(full), { recursive: true });
    await writeFile(full, content, "utf8");
  }
  return dir;
}

// A v0.2-rich concept: generated + human verification + freshness + status.
const V02_HUMAN_BODY =
  "---\ntype: policy\ntitle: Trust discipline\ngenerated:\n  by: human:okfhub-team\n  at: '2026-08-06'\nverified:\n  - by: human:kliu\n    at: '2026-07-01'\nstale_after: '2027-01-01'\nstatus: active\n---\n\n# Trust discipline\n\nDated evidence, never verdicts.\n";

// A machine-verified concept (agent verifier, no human).
const V02_MACHINE_BODY =
  "---\ntype: object\ntitle: Sample\ngenerated:\n  by: agent:claude-code\n  at: '2026-07-02'\nverified:\n  - by: agent:claude-code\n    at: '2026-07-02'\n---\n\n# Sample\n\nA machine-confirmed concept.\n";

// A v0.1 concept: only `type` — no v0.2 families at all.
const V01_BODY =
  "---\ntype: metric\ntitle: Plain\n---\n\n# Plain\n\nNo v0.2 frontmatter.\n";

test("trust: v0.2-rich bundle → extracted fields + tier counts + dated-evidence rows", async () => {
  const dir = await makeBundle({
    "index.md": "---\ntitle: idx\n---\n\n# Index\n",
    "trust-discipline.md": V02_HUMAN_BODY,
    "sample.md": V02_MACHINE_BODY,
  });
  try {
    const artifacts = await materializeConcepts(dir);
    const ts = summarizeTrustBundle(artifacts);
    // Tier roll-up: human + machine + unverified(index has no frontmatter type?
    // index.md is RESERVED — skipped by parseBundle; both concepts verified).
    assert.equal(ts.total, 2);
    assert.equal(ts.humanReviewed, 1);
    assert.equal(ts.machineConfirmed, 1);
    assert.equal(ts.unverified, 0);
    assert.deepEqual(ts.tier_counts, { unverified: 0, machineConfirmed: 1, humanReviewed: 1 });
    // Extracted generated family rides the structured field (the FIRST found
    // in walk order — deterministic per bundle) + dated rows for every entry.
    const genPairs = [
      ["human:okfhub-team", "2026-08-06"],
      ["agent:claude-code", "2026-07-02"],
    ];
    assert.ok(
      genPairs.some(([by, at]) => ts.generated?.by === by && ts.generated?.at === at),
      "generated is one of the concepts' generated entries",
    );
    const rowTexts = ts.rows.map((r) => r.text);
    assert.ok(rowTexts.some((t) => t.includes("generated by human:okfhub-team")), "generated row present");
    assert.ok(rowTexts.some((t) => t.includes("verified by human:kliu")), "human verified row present");
    assert.ok(rowTexts.some((t) => t.includes("verified by agent:claude-code")), "machine verified row present");
    // Freshness roll-up from the earliest stale_after.
    assert.equal(ts.freshness?.stale_after, "2027-01-01");
    assert.ok(["fresh", "stale", "unknown"].includes(ts.freshness?.status));
    assert.ok(rowTexts.some((t) => t.includes("stale_after 2027-01-01")), "freshness row present");
    // D-09: NEVER badge glyphs in row content.
    for (const t of rowTexts) assert.ok(!/🟢|🔵|🟡/.test(t), `no badge glyph in: ${t}`);
    // The logic version + build stamp.
    assert.equal(ts.trust_logic_version, 1);
    assert.equal(typeof ts.checked_at, "string");
  } finally {
    await rm(dir, { recursive: true, force: true });
  }
});

test("trust: no v0.2 frontmatter → honest all-unverified summary (never undefined, never an error)", async () => {
  const dir = await makeBundle({
    "index.md": "---\ntitle: idx\n---\n\n# Index\n",
    "plain.md": V01_BODY,
  });
  try {
    const artifacts = await materializeConcepts(dir);
    const ts = summarizeTrustBundle(artifacts);
    assert.equal(ts.total, 1);
    assert.equal(ts.unverified, 1);
    assert.equal(ts.machineConfirmed, 0);
    assert.equal(ts.humanReviewed, 0);
    assert.deepEqual(ts.tier_counts, { unverified: 1, machineConfirmed: 0, humanReviewed: 0 });
    // The honest absence row renders the count.
    assert.ok(ts.rows.some((r) => r.text.includes("no verification frontmatter")));
    // No v0.2 families extracted — structured generated/freshness stay absent.
    assert.equal(ts.generated, undefined);
    assert.equal(ts.freshness, undefined);
  } finally {
    await rm(dir, { recursive: true, force: true });
  }
});

test("trust: malformed v0.2 field degrades the concept to unverified, never aborts", async () => {
  // verified: "garbage" (a string, not an array) — mirrors the website's
  // never-throw contract (UI-SPEC Test 4; one bad concept never blocks the
  // bundle summary).
  const dir = await makeBundle({
    "index.md": "---\ntitle: idx\n---\n\n# Index\n",
    "garbage.md":
      "---\ntype: object\ntitle: Garbage\nverified: garbage\n---\n\n# Garbage\n",
    "good.md": V02_MACHINE_BODY,
  });
  try {
    const artifacts = await materializeConcepts(dir);
    const ts = summarizeTrustBundle(artifacts);
    assert.equal(ts.total, 2);
    assert.equal(ts.unverified, 1);
    assert.equal(ts.machineConfirmed, 1);
    assert.equal(ts.humanReviewed, 0);
  } finally {
    await rm(dir, { recursive: true, force: true });
  }
});

test("trust: empty artifact set → honest zeros, never throws", () => {
  const ts = summarizeTrustBundle([]);
  assert.equal(ts.total, 0);
  assert.equal(ts.unverified, 0);
  assert.equal(ts.machineConfirmed, 0);
  assert.equal(ts.humanReviewed, 0);
  assert.ok(Array.isArray(ts.rows));
});
