// build-registry-openwiki.test.mjs — D-08 OpenWiki trace-detection tests
// (Phase 10, Plan 10-01). node:test + node:assert/strict + .mjs — MATCHES the
// existing registry .test.mjs files (NOT vitest).
//
// OpenWiki (langchain-ai/openwiki) stamps a `<!-- OPENWIKI:START -->…END -->`
// marker comment around the block it rewrites on each run (10-CONTEXT D-08 /
// 10-RESEARCH). Detection is build-time + repo-level: detectOpenwiki scans the
// materialized concept bodies for the START marker and sets the additive
// `openwiki_detected` boolean on the bundle. Detection only — NO integration.
//
// FIXTURE DISCIPLINE: hermetic in-test tmp bundle dirs, same as
// build-registry-materialize.test.mjs.
import { test } from "node:test";
import assert from "node:assert/strict";
import { mkdtemp, mkdir, writeFile, rm } from "node:fs/promises";
import { join, dirname } from "node:path";
import { tmpdir } from "node:os";
import { materializeConcepts, detectOpenwiki } from "../scripts/build-registry.mjs";

/** Build a tmp bundle dir with the given {relPath: content} files. Returns dir. */
async function makeBundle(files) {
  const dir = await mkdtemp(join(tmpdir(), "okfhub-openwiki-"));
  for (const [relPath, content] of Object.entries(files)) {
    const full = join(dir, relPath);
    await mkdir(dirname(full), { recursive: true });
    await writeFile(full, content, "utf8");
  }
  return dir;
}

// A concept body carrying the OpenWiki marker block (the trace OpenWiki leaves).
const OPENWIKI_BODY =
  "---\ntype: page\ntitle: Home\n---\n\n<!-- OPENWIKI:START -->\n# Home\n\nGenerated by OpenWiki.\n<!-- OPENWIKI:END -->\n";

// A plain concept body with no marker.
const PLAIN_BODY =
  "---\ntype: metric\ntitle: Sample\n---\n\n# Sample\n\nA plain concept body.\n";

test("openwiki: marker detection — marker present → true", async () => {
  const dir = await makeBundle({
    "index.md": "---\ntitle: idx\n---\n\n# Index\n",
    "home.md": OPENWIKI_BODY,
    "other.md": PLAIN_BODY,
  });
  try {
    const artifacts = await materializeConcepts(dir);
    assert.equal(detectOpenwiki(artifacts), true, "a concept body with the marker → openwiki_detected");
  } finally {
    await rm(dir, { recursive: true, force: true });
  }
});

test("openwiki: marker detection — marker absent → false", async () => {
  const dir = await makeBundle({
    "index.md": "---\ntitle: idx\n---\n\n# Index\n",
    "sample.md": PLAIN_BODY,
  });
  try {
    const artifacts = await materializeConcepts(dir);
    assert.equal(detectOpenwiki(artifacts), false, "no marker anywhere → NOT openwiki_detected");
  } finally {
    await rm(dir, { recursive: true, force: true });
  }
});

test("openwiki: the END marker alone does NOT count (START is the rewrite-block anchor)", async () => {
  // Detection keys on the START marker only — a body that merely mentions the
  // END marker (e.g. quoted in prose) is not an OpenWiki trace.
  const dir = await makeBundle({
    "sample.md":
      "---\ntype: page\ntitle: Quoted\n---\n\nThe marker pair ends with <!-- OPENWIKI:END --> per the docs.\n",
  });
  try {
    const artifacts = await materializeConcepts(dir);
    assert.equal(detectOpenwiki(artifacts), false);
  } finally {
    await rm(dir, { recursive: true, force: true });
  }
});

test("openwiki: empty concept set → false (never throws)", async () => {
  assert.equal(detectOpenwiki([]), false);
});
